- name: Uruchom curl parrot.live i pokaż wynik w AWX
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Sprawdź czy curl jest zainstalowany
      ansible.builtin.shell: which curl
      register: curl_check
      changed_when: false
      failed_when: curl_check.rc != 0
      ignore_errors: false

    - name: Pobierz animację z parrot.live z limitem czasu
      ansible.builtin.shell: timeout 3s curl -s parrot.live
      register: curl_output
      changed_when: false

    - name: Pokaż wynik w logach AWX
      ansible.builtin.debug:
        msg: |
          🦜 Wynik curl z parrot.live:

          {{ curl_output.stdout | default('❌ Brak odpowiedzi lub przerwane.') }}
