---
- name: Wyswietl animację z parrot.live
  hosts: 10.10.8.82
  gather_facts: false
  become: false

  tasks:
    - name: Wyslij zapytanie curl do parrot.live (timeout 5s)
      ansible.builtin.shell: "timeout 5 curl parrot.live"
      register: wynik
      failed_when: false

    - name: Pokaz wynik animacji w AWX
      ansible.builtin.debug:
        msg: |
          ➤ Stan wykonania: {{ '✅ SUKCES (timeout)' if wynik.rc == 124 else '✅ SUKCES' if wynik.rc == 0 else '❌ BŁĄD' }}
          ➤ Odpowiedź:
          {{ wynik.stdout | default('Brak odpowiedzi z serwera') }}
