---
- name: Wyswietl animację z ascii.live/can-you-hear-me
  hosts: 10.10.8.82
  gather_facts: false
  become: true

  tasks:
    - name: Wyslij zapytanie curl do ascii.live/can-you-hear-mee (timeout 5s)
      ansible.builtin.shell: "curl ascii.live/can-you-hear-me"
      register: wynik
      failed_when: false

    - name: Pokaz wynik animacji w AWX
      ansible.builtin.debug:
        msg: |
          ➤ Stan wykonania: {{ '✅ SUKCES (timeout)' if wynik.rc == 124 else '✅ SUKCES' if wynik.rc == 0 else '❌ BŁĄD' }}
          ➤ Odpowiedź:
          {{ wynik.stdout | default('Brak odpowiedzi z serwera') }}
