---
- name: Uruchom animację z parrot.live
  hosts: 10.10.8.82
  become: false

  tasks:
    - name: Wyslij zapytanie curl do parrot.live (timeout 5s)
      ansible.builtin.shell: "timeout 5 curl parrot.live"
      register: wynik
      ignore_errors: true

    - name: Pokaz wynik w AWX
      ansible.builtin.debug:
        msg: |
          Zadanie zakończone: {{ 'SUKCES' if wynik.rc == 0 else 'BŁĄD' }}
          Wynik:
          {{ wynik.stdout | default('BRAK ODPOWIEDZI') }}
