- name: Pokaz komunikat przez wall
  hosts: all
  become: true
  tasks:
    - name: Zainstaluj figlet jeśli potrzeba
      apt:
        name: figlet
        state: present
      when: ansible_facts.os_family == "Debian"

    - name: Pokaz komunikat
      shell: |
        figlet -c "Siema forys" | wall
