- name: Uruchomienie apt update na zdalnym serwerze
  hosts: all
  become: true
  tasks:
    - name: Wykonaj sudo apt update
      ansible.builtin.shell: apt update
      register: wynik_aktualizacji

    - name: Pokaz wynik aktualizacji
      ansible.builtin.debug:
        var: wynik_aktualizacji.stdout_lines
