---
- name: Zrób pliki na systemie i coś w nich zmień
  hosts: 10.10.8.82
  become: yes
  tasks:
    - name: Tworzenie plików
      ansible.builtin.shell: sudo mkdir -p pliki && cd pliki && sudo touch plik.txt && echo "linia 1" >> plik.txt && echo "docker 1" >> plik.txt && echo "docker 2" >> plik.txt && echo "ansible 1" >> plik.txt && cat plik.txt | grep "docker" > plik2.txt
