- name: Ustawienia MikroTik
  hosts: all
  gather_facts: no
  connection: community.routeros

  tasks:
    - name: Dodaj adres do listy adresów
      community.routeros.api_modify:
        resource: "/ip/firewall/address-list"
        data:
          list: "adres"
          address: "192.168.88.110"

    - name: Dodaj kolejny adres do listy adresów
      community.routeros.api_modify:
        resource: "/ip/firewall/address-list"
        data:
          list: "adres"
          address: "11.11.11.12"

    - name: Dodaj filtr wejściowy - established/related
      community.routeros.api_modify:
        resource: "/ip/firewall/filter"
        data:
          chain: "input"
          connection-state: "established,related"
          action: "accept"
