---
- name: Konfiguracja MikroTik przez SSH z kluczem
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_private_key_file: /runner/artifacts/290/ssh_key_data
    ansible_ssh_extra_args: >
     -o IdentitiesOnly=yes
     -o StrictHostKeyChecking=no

  tasks:
    - name: Uruchomienie blok komend MikroTik w terminalu
      raw: |
        /ip firewall address-list
        add list=adres address=192.168.88.110
        add list=adres address=11.11.11.12
        add list=adres address=10.10.11.131

        /ip firewall filter
        add chain=input connection-state=established,related action=accept
        add chain=input protocol=tcp dst-port=22 src-address-list=adres
        add chain=input protocol=tcp dst-port=22 action=drop
    - name: Potwierdzenie poprawnego zakończenia
      debug:
        msg: "Playbook zakończył się poprawnie"
