- name: Konfiguracja firewall na Mikrotikach przez SSH (expect)
  hosts: all
  gather_facts: no
  vars:
    mikrotik_user: admin
    # Zalecam umieścić hasło w cudzysłowie; jeśli używasz ansible-vault -> jeszcze lepiej.
    mikrotik_pass: "JC3WROCN4W"
    # timeout w sekundach dla expect
    expect_timeout: 30

  tasks:
    - name: Wykonaj serię poleceń RouterOS przez SSH używając expect
      expect:
        command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ mikrotik_user }}@{{ inventory_hostname }}
        responses:
          # dopasowujemy zarówno "Password:" jak i "password:" — używamy fragmentu 'assword:' jako regexp
          'assword:': "{{ mikrotik_pass }}"
          # dopasowujemy prompt MikroTik (np. [admin@MikroTik] > ) — prosty regexp dla linii z ] >
          '\[.*\]\s*>': |
            /ip firewall address-list add list=adres address=192.168.88.110
            /ip firewall address-list add list=adres address=11.11.11.12
            /ip firewall filter add chain=input connection-state=established,related action=accept
            /ip firewall filter add chain=input protocol=tcp dst-port=22 src-address-list=adres action=accept
            /ip firewall filter add chain=input protocol=tcp dst-port=22 action=drop
            quit
        timeout: "{{ expect_timeout }}"
      register: expect_out

    - name: Pokaż wynik (opcjonalnie)
      debug:
        var: expect_out.stdout_lines
