---
- name: Pokaz komunikatu na zdalnym serwerze
  hosts: all
  become: false  # lub true, jeśli potrzebujesz roota
  tasks:
    - name: Wyswietl komunikat
      ansible.builtin.shell: echo "Witaj ze świata Ansible!"
      register: wynik

    - name: Pokaz wynik na lokalnym ekranie
      ansible.builtin.debug:
        var: wynik.stdout
