- name: Pokaz komunikat w terminalu i wynik w AWX
  hosts: 10.10.8.82
  become: yes
  tasks:
    - name: Wyslij komunikat do terminala uzytkownikow
      ansible.builtin.shell: echo "🐧 Hej! To komunikat z Ansible przez AWX." | wall
      register: wynik

    - name: Pokaz wynik w logach AWX
      ansible.builtin.debug:
        msg: |
          ✅ Zadanie wykonane poprawnie.
          💬 Komunikat został wysłany do terminali użytkowników.
          🔧 Kod wyjścia: {{ wynik.rc }}
          🧾 Stdout: {{ wynik.stdout }}
